name: 'Create AWS KMS key'
description: 'Create AWS KMS key if it does not exist.'
inputs:
  key-alias:
    description: 'Alias of the key'
    required: true
outputs:
  id:
    description: 'String id of the key.'
runs:
  using: 'node24'
  main: '../dist/create-kms-key/index.js'