name: 'Create AWS S3 bucket'
description: 'Create AWS S3 bucket if it does not exist.'
inputs:
  bucket-name:
    description: 'Name of the bucket'
    required: true
  is-public:
    description: 'Can the bucket contain publicly accessible objects.'
    required: false
runs:
  using: 'node24'
  main: '../dist/create-s3-bucket/index.js'